version: 2.1
executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_XMLDOC_MODE: skip

workflows:
  build-and-push:
    jobs:
      - build-test:
          project: AgonesSdkCsharp
          filters:
            tags:
              only: /.*/
      - build-push:
          context: nuget
          project: AgonesSdkCsharp
          requires:
            - build-test
          filters:
            tags:
              only: /^[0-9](\.[0-9]){2}$/
            branches:
              ignore: /.*/

jobs:
  build-test:
    executor: dotnet
    parameters:
      project:
        type: string
    steps:
      - checkout
      - run: dotnet build -c Debug
      - run: dotnet test -c Debug < /dev/null
      # - run: dotnet tool install -g dotnet-reportgenerator-globaltool
      # - run: dotnet test -c Debug --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Include=[<< parameters.project >>.*]*); echo $x;
      # - run: curl -s https://codecov.io/bash > codecov
      # - run: chmod +x codecov
      # - run: ./codecov -f ./tests/<< parameters.project >>.Tests/coverage.opencover.xml
  build-push:
    executor: dotnet
    parameters:
      project:
        type: string
    steps:
      - checkout
      - run:
          name: deploy when exists tag
          command: |
            dotnet build -c Release -p:Version=${CIRCLE_TAG}
            dotnet test -c Debug < /dev/null
            dotnet pack c Release --no-build -p:Version=${CIRCLE_TAG}
            dotnet nuget push ./bin/Release/<< parameters.project >>.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY} --skip-duplicate
          working_directory: ./src/<< parameters.project >>
      - store_artifacts:
          path: ./src/<< parameters.project >>/bin/Release
          destination: ./<< parameters.project >>/
